services:
  registry:
    image: registry
    container_name: registry
    restart: unless-stopped
    ports:
      - "80:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registry:/data

volumes:
  registry:
